```{r}
library(ggplot2)
library(cladina)

n <- 300
d <- generate_data(n, 2, 2, f_x_rnorm_dist, f_signal_cos, f_noise_rnorm_scaled)

```

```{r}
ggplot(d, aes(Independent, Dependent)) + geom_point()
```

```{r}
target_nknots <- 7
res <- choose_model(d, Dependent, Independent, max_nsknots = target_nknots)

plot_model(d, Dependent, Independent, res$ns$model)
plot_model(d, SignalMeasured, Independent, res$ns$model)
plot_rstandard(d, res$ns$model)

plot_model(d, Dependent, Independent, res$mfp$model)
plot_model(d, SignalMeasured, Independent, res$mfp$model)
plot_rstandard(d, res$mfp$model)

plot_model(d, Dependent, Independent, res$ns_nu$model)
plot_model(d, SignalMeasured, Independent, res$ns_nu$model)
plot_rstandard(d, res$ns_nu$model)
```

```{r}
target_nknots <- 7
res <- choose_splines_thorough(d, Dependent, Independent, max_nknots = target_nknots)

plot_model(d, Dependent, Independent, res$uniform$model)
plot_model(d, SignalMeasured, Independent, res$uniform$model)
plot_rstandard(d, res$uniform$model)

plot_model(d, Dependent, Independent, res$distinct$model)
plot_model(d, SignalMeasured, Independent, res$distinct$model)
plot_rstandard(d, res$distinct$model)

plot_model(d, Dependent, Independent, res$quantile$model)
plot_model(d, SignalMeasured, Independent, res$quantile$model)
plot_rstandard(d, res$quantile$model)
```
