---
title: "experiments.Rmd"
author: "Jo Inge Arnes"
date: "2023-01-07"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, include = FALSE}
library(dplyr)
library(ggplot2)
library(ggh4x)
library(scales)
library(knutar)
library(curry)
library(rvmethod)
```

## Results

```{r single-sample-figures, include = FALSE}

name_and_bic <- function(name, mod) {
  k <- length(extract_knots(mod)$knots)
  return(paste(name, "~'curve (BIC: ", round(BIC(mod)), ")'", sep = ""))
}

plot_curves_and_observations <- function(d, f_curve, mod0, mod1, curve_name) {
  n = 250

  boundaries <- extract_knots(mod1)$Boundary.knots
    
  #x <- seq(from = min(boundaries[[1]]), to = max(boundaries[[2]]), length.out = n)
  x <- seq(from = min(d$IndependentRaw), to = max(d$IndependentRaw), length.out = n)  
  y <- unlist(lapply(x, f_curve))
  d_x <- data.frame(IndependentRaw = x)


  d_o <- d_x #   %>% filter(between(IndependentRaw, boundaries[[1]], boundaries[[2]]))
  n_o <- nrow(d_o)
  y0 <- predict(mod0, newdata = d_o)
  y1 <- predict(mod1, newdata = d_o)

  true_label <- "'true curve'"
  a0_label <- name_and_bic("a[1]", mod0)
  a1_label <- name_and_bic("a[2]", mod1)

  d2 <- data.frame("IndependentRaw" = x, "DependentRaw" = y, "Curves" = replicate(n, true_label))
  d2 <- rbind(d2, data.frame("IndependentRaw" = d_o$IndependentRaw, "DependentRaw" = y0, "Curves" = replicate(n_o, a0_label)))
  d2 <- rbind(d2, data.frame("IndependentRaw" = d_o$IndependentRaw, "DependentRaw" = y1, "Curves" = replicate(n_o, a1_label)))

  d2$Curves <- factor(d2$Curves,
                      levels = c(true_label, a0_label, a1_label))

  fig <- ggplot(d2, aes(IndependentRaw, DependentRaw))
  fig <- fig + force_panelsizes(rows = unit(2.28, "in"), cols = unit(3.7, "in"))  
  fig <- fig + theme_bw()
  fig <- fig + geom_point(data = d, aes(IndependentRaw, DependentRaw), shape = 1, color = "gray60", size = 1)  
  fig <- fig + scale_linetype_manual(values = c("solid", "twodash", "solid"),
                     labels = parse_format()(c(true_label, a0_label, a1_label)))
  fig <- fig + scale_color_manual(values = c("gray80", "black", "black"),
                     labels = parse_format()(c(true_label, a0_label, a1_label)))
  fig <- fig + scale_size_manual(values=c(1, 0.5, 0.5),
                     labels = parse_format()(c(true_label, a0_label, a1_label)))
  fig <- fig + geom_line(aes(linetype = Curves, color = Curves, size = Curves))
  fig <- fig + geom_vline(xintercept = boundaries)
  fig <- fig + guides(shape = "none")
  fig <- fig + theme(legend.position = "top",
                     legend.justification = c("left","top"),
                     legend.box.just = "left",
                     legend.title = element_blank(),
                     legend.margin = margin(0, 0, 0, 0),
                     legend.spacing.x = unit(0, "mm"),
                     legend.spacing.y = unit(0, "mm"))
  fig <- fig + ggtitle("True and Fitted Curves Example")
  fig <- fig + xlab(parse_format()("'Predictor'~X")) 
  fig <- fig + ylab(parse_format()("'Response'~Y"))
  fig <- fig + annotate(geom = "point", x = extract_knots(mod0)$knots, y = Inf, shape = 25, fill = "black", size = 2)
  fig <- fig + annotate(geom = "point", x = extract_knots(mod1)$knots, y = -Inf, shape = 24, fill = "black", size = 2)
  
  return(fig)
}
```

## Example data set and models

```{r, include = FALSE}
f_noise <- function(xs) {
  return(rnorm(length(xs), 0, 0.1))
}

f_signal <- function(x, curve_name) {
  y <- switch(curve_name,
         "Trigonometric" = cos(1.5*pi * x),
         "Logistic" = 1 / (1 + exp(27 - 12*x)),
         "Runge" = 1 / (1 + ((3/2)*x - 4)^2),
         "Gaussians" = 1.5*gaussfunc(x, 1, 0.5) + gaussfunc(x, 2.75, 0.5))
    return(y)
}

f_x_dist  <- function(n) {
  return(rlnorm(n, meanlog = 0.5, sdlog = 0.35))
}

f_x_unif <-  function(n) {
  return(runif(n, 0, 4))
}

generate_example_data <- function(n, curve_name) {
  f_signal_curried <- f_signal %-<% curve_name
  
  if (curve_name == "Gaussians")
    f_x_dist <- f_x_unif
  
  d <- generate_data(n, 2, 2, f_x_dist, f_signal_curried, f_noise)
  return(d)
}
```

```{r}
seed <- 4
curve_name <- "Trigonometric"

#seed <- 3
#curve_name <- "Logistic"

#seed <- 1
#curve_name <- "Runge"

#seed <- 8
#curve_name <- "Quintic"

#seed <- 3
#curve_name <- "Gaussians"

set.seed(seed)

d <- generate_example_data(250, curve_name)

boundary_knots <-c(quantile(d$IndependentRaw, .05), quantile(d$IndependentRaw, .95))
#boundary_knots <- NA

#d <- d %>% filter(between(IndependentRaw, quantile(d$IndependentRaw, .05), quantile(d$IndependentRaw, .95)))

max_knots <- 3
suggested_cnt <- suggest_knotcount(d, DependentRaw, IndependentRaw, max_nknots = max_knots, boundary_knots = boundary_knots)
m0 <- model_by_count(d, DependentRaw, IndependentRaw, suggested_cnt$nknots, boundary_knots = boundary_knots)
m1 <- choose_splines(d, DependentRaw, IndependentRaw,  max_nknots = max_knots, boundary_knots = boundary_knots)$model
```

## Including Plots

```{r plot-curves, echo = FALSE}
f_signal_curried <- f_signal %-<% curve_name

fig <- plot_curves_and_observations(d, f_signal_curried, m0, m1, curve_name)
plot(fig)

```

Save image

```{r}
now_time <- Sys.time()

file_name <- paste("example_figs/", curve_name, "-seed-", seed, ".png", sep = "")
file_name <- gsub("[ :]", "-", file_name)
file_name <- tolower(file_name)

ggsave(file_name, plot = fig, device = "png", units = "in", dpi = "print", height = 3.5, width = 4.5)
```
