---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
library(ggplot2)
library(ggpubr)
library(ggh4x)
library(scales)
library(cladina)

f_noise <- function(xs) {
 return(rnorm(length(xs), 0, 0.1))
}

f_signal <- function(x) {
  y <- cos(pi * x)
  return(y)
}

f_x_dist  <- function(n) {
  return(rlnorm(n, meanlog = 0.5, sdlog = 0.35))
}

name_and_bic <- function(name, mod) {
  k <- length(extract_knots(mod)$knots)
  return(paste(name, "~'(Knots: ", k, ", BIC: ", round(BIC(mod)), ")'", sep = ""))
}

create_figure <- function(d, mod, title) {
  x <- seq(from = min(d$IndependentRaw), to = max(d$IndependentRaw), length.out = 200)
  y <- unlist(lapply(x, f_signal))
  d_true <- data.frame("x" = x, "y" = y)
  
  knots <- extract_knots(mod)
  boundaries <- knots$Boundary.knots
  knots <-knots$knots 

  x_fit <- d_true %>% rename(IndependentRaw = x)
  # x_fit <- d_true %>% filter(between(x, boundaries[[1]], boundaries[[2]])) %>% rename(IndependentRaw = x)
  y_hat <- predict(mod, newdata = x_fit)
  d_hat <- data.frame(x = x_fit$IndependentRaw, fitted = y_hat)
  
  
  fig <- ggplot()
  fig <- fig + theme_bw()
#  fig <- fig + force_panelsizes(rows = unit(3.5/2, "in"), cols = unit(3.5, "in"))
  fig <- fig + geom_vline(xintercept = knots, linetype = "dashed", color = "gray60")
  fig <- fig + geom_line(data = d_true, aes(x = x, y = y), linetype = "solid", color = "gray80", size = 1)

  fig <- fig + geom_point(data = d, aes(x = IndependentRaw, y = DependentRaw), shape = 1, color = "gray60", size = 1)
  fig <- fig + geom_line(data = d_hat, aes(x = x, y = fitted), linetype = "solid", color = "black", size = 0.5)
  
  fig <- fig + geom_vline(xintercept = boundaries) 
  
  fig <- fig + ggtitle(title)
  fig <- fig + xlab(parse_format()("'Predictor'~X")) 
  fig <- fig + ylab(parse_format()("'Response'~Y"))
  return(fig)
}


set.seed(4)

d <- cladina::generate_data(250, 2, 2, f_x_dist, f_signal, f_noise)

k_max <- 3

boundary_knots <-c(quantile(d$IndependentRaw, .05), quantile(d$IndependentRaw, .95))

res <- cladina::suggest_splines(d, DependentRaw, IndependentRaw, k_max, 
                                all_knots = TRUE, 
                                boundary_knots = boundary_knots)

i_max <- length(res$all_knots)
fig_lowest_knots <- i_max
knots_indices <- c(1, 6, 11, fig_lowest_knots)

figs <- lapply(knots_indices, function(i) {
  knots <- res$all_knots[[i]]
  mod <- cladina::model_by_knots(d, DependentRaw, IndependentRaw, 
                                 knots, res$Boundary.knots)
  
  print(knots)
  
  return(create_figure(d, 
                mod, 
                paste("Inner knots: ", length(knots), ", BIC: ", round(BIC(mod), 0), sep = "")))
})

knot_removal_fig <- ggarrange(figs[[1]], figs[[2]], figs[[3]], figs[[4]], nrow = 2, ncol = 2)

ggsave("example_figs/iteratively-removing-knots.png", plot = knot_removal_fig, device = "png", dpi = "print", height = 8.4/2, width = 8.4)

k_lowest <- length(res$all_knots[[fig_lowest_knots]])
mod_standard <- model_by_count(d, DependentRaw, IndependentRaw, k_lowest, 
                               boundary_knots = boundary_knots)
fig_standard <- create_figure(d, 
                          mod_standard, 
                          paste("Inner knots: ", k_lowest, ", BIC: ", round(BIC(mod_standard), 0), sep = ""))

#fig_standard = fig_standard + force_panelsizes(rows = unit(3.5/2, "in"), cols = unit(3.5/2, "in"))

fig_standard_compared <- ggarrange(figs[[4]], fig_standard, nrow = 1, ncol = 2)

plot(fig_standard_compared)

ggsave("example_figs/standard.png", plot = fig_standard_compared, device = "png", height = 4.2/2, width = 8.4)
  
```

```{r}

knot_cnt_suggestions <- suggest_knotcount(d, DependentRaw, IndependentRaw, max_nknots = 50, 
                                          all_scores = TRUE, boundary_knots = boundary_knots)
d_knot_bics <- data.frame(
  Knots = unlist(knot_cnt_suggestions$all_scores$n_knots), BIC = unlist(knot_cnt_suggestions$all_scores$scores))


fig_bic_knot_cnts <- ggplot(d_knot_bics, aes(Knots, BIC)) + 
  theme_bw() +
  force_panelsizes(rows = unit(3.5, "in"),
                   cols = unit(7, "in")) +
  geom_point(shape = 15, color = "gray50") +
  scale_x_continuous(breaks = seq(0, 50, 5)) +
  ggtitle("BIC scores for RCS regressions with 0 to 50 inner knots")
  
ggsave("example_figs/bic-and-knot-counts.png", plot = fig_bic_knot_cnts, device = "png", height = 4.2, width = 8)
```
