```{r}
library(cladina)
library(dplyr)

```

```{r}

f_noise <- function(xs) {
  return(rnorm(length(xs), 0, 0.1))
}

f_x_dist  <- function(n) {
  return(rlnorm(n, meanlog = 0.5, sdlog = 0.35))
}

# Trigonometric

f_signal_trigonometric <- function(x) {
  return(cos(pi * x))
}

generate_trigonometric <- function(n) {
  d <- generate_data(n, 2, 2, f_x_dist, f_signal_trigonometric, f_noise)
  return(d)
}


# Logistic

f_signal_logistic <- function(x) {
  return(1 / (1 + exp(27 - 12*x)))
}

generate_logistic <- function(n) {
  d <- generate_data(n, 2, 2, f_x_dist, f_signal_logistic, f_noise)
}


# Runge

f_signal_runge <- function(x) {
  return(1 / (1 + (1.5*x - 4)^2))
}

generate_runge <- function(n) {
  d <- generate_data(n, 2, 2, f_x_dist, f_signal_runge, f_noise)
}

# Quintic function

f_signal_quintic <- function(x) {
  return(((4/3)*x - 5)*((4/3)*x - 4)*((4/3)*x - 3)*((4/3)*x - 2)*((4/3)*x-1))
}

generate_quintic <- function(n) {
  d <- generate_data(n, 2, 2, f_x_dist, f_signal_quintic, f_noise)
  return(d)
}

```

```{r}

compute_loss <- function(actual, predicted) {
  n <- length(predicted)
  sse <- sum((actual - predicted)**2)
  return(sse / n)
}

single_sample_experiment <- function(i, m, n, gen_fn, max_knots) {
  # Generate data
  d <- gen_fn$fn(n)
  d$Xp <- d$IndependentRaw
  d$Xr <- d$DependentRaw
  d$Y <- d$SignalRaw
  
  # 5% and 95% outer boundaries
  d <- d %>% filter(between(Xp, quantile(Xp, .05), quantile(Xp, .95)))
  
  # Get the best model given that knots are placed at quantiles within a maximum number knots
  suggested <- suggest_knotcount(d, Xr, Xp, max_knots, stats::BIC)
  nknots_a1 <-suggested$nknots
  mod_a1 <- model_by_count(d, Xr, Xp, nknots_a1)
  bic_a1 <- stats::BIC(mod_a1)

  # Get the best model given our approach within a maximum number knots
  res_a2 <- choose_splines(d, Xr, Xp, max_nknots = max_knots, icr_fn = stats::BIC,
                           cost_fn = stats::BIC)
  nknots_a2 <- length(res_a2$knots$knots)
  mod_a2 <- res_a2$model
  bic_a2 <- res_a2$score
  
  b_knots <- res_a2$knots$Boundary.knots
  
  # Generate 2*m observations from the same distribution as d
  d_m <- gen_fn$fn(m * 2)

  # Only keep values within boundaries, and select m of these observations
  d_m <- d_m %>% 
    filter(between(IndependentRaw, b_knots[[1]], b_knots[[2]])) %>%
    slice(1:m)
  
  d_m$Xp <- d_m$IndependentRaw
  d_m$Xr <- d_m$DependentRaw
  d_m$Y <- d_m$SignalRaw
  
  # Make predictions and compute loss for a1 and a2
  p_a1 <- compute_loss(d_m$Y, predict(mod_a1, newdata = d_m))  
  p_a2 <- compute_loss(d_m$Y, predict(mod_a2, newdata = d_m))

  # Return a result row
  res <- list(
    "m" = m,
    "n" = n,
    "gen_fn" = gen_fn$name,
    "bic_a1" = bic_a1, "nknots_a1" = nknots_a1, "p_a1" = p_a1,
    "bic_a2" = bic_a2, "nknots_a2" = nknots_a2, "p_a2" = p_a2,
    "bic_diff" = bic_a1 - bic_a2, "nknots_diff" = nknots_a1 - nknots_a2, 
    "p_diff" = p_a1 - p_a2)  
  
  R.utils::printf(".")
  
  return(res)
}

multiple_sample_experiments <- function(n, m, gen_fn, rep_cnt, max_knots) {
  res_list <- lapply(1:rep_cnt, single_sample_experiment, gen_fn = gen_fn, m = m, n = n, max_knots = max_knots)
  res_df <- as.data.frame(data.table::rbindlist(res_list))
  return(res_df)
}

generator_sample_experiments <- function(gen_fn, sample_sizes, m, samples_per_set, max_knots) {
  # Run experiments with same generator, different n, sets of many samples per n
  res_df_list <- lapply(sample_sizes, multiple_sample_experiments, m = m, gen_fn = gen_fn, rep_cnt = samples_per_set, max_knots = max_knots)
  
  res_df <- bind_rows(res_df_list, .id = "generator_sample_index")
  
  return(res_df)
}
```

```{r}
seed <- 1
set.seed(seed)

max_knots <- 4
sample_sizes <- c(250)
samples_per_set <- 1000
B <- 2000


## List of functions for for generating samples for different curves
generators <- list(
  list("name" = "Quintic", "fn" = generate_quintic, "curve_fn" = f_signal_quintic),
  list("name" = "Logistic", "fn" = generate_logistic, "curve_fn" = f_signal_logistic),
  list("name" = "Runge", "fn" = generate_runge, "curve_fn" = f_signal_runge),
  list("name" = "Trigonometric", "fn" = generate_trigonometric, "curve_fn" = f_signal_trigonometric)
  )

res_df_list <- lapply(generators, generator_sample_experiments, sample_sizes = sample_sizes, m = B, samples_per_set = samples_per_set, max_knots = max_knots)

df_all_results <- bind_rows(res_df_list, .id = "generator_index")

experiment_finished_time <- Sys.time()

print('Completed')
```

```{r, save-result-files}
# Save results
file_name <- paste("experiment-results-", experiment_finished_time, sep = "")
file_name <- gsub("[ :]", "-", file_name)
saveRDS(df_all_results, file = paste(file_name, ".Rds", sep = ""))
write.csv(df_all_results, paste(file_name, ".csv", sep = ""), row.names = FALSE)

# Compute sample statistics for the results
df_sample_stats <- df_all_results %>%
  group_by(generator_index, generator_sample_index) %>%
  summarise_at(vars(bic_diff, bic_a1, bic_a2, p_diff, p_a1, p_a2, nknots_a1, nknots_a2, nknots_diff, n, m), list(mean = mean, median = median, sd = sd))

# Save the result sample statistics
file_name <- paste("experiment-results-sample-stats-", experiment_finished_time, sep = "")
file_name <- gsub("[ :]", "-", file_name)
saveRDS(df_sample_stats, file = paste(file_name, ".Rds", sep = ""))
write.csv(df_sample_stats, paste(file_name, ".csv", sep = ""), row.names = FALSE)
```

Estimation of population mean differences for BIC scores for a_1 and a_2 models

```{r}
library(boot)

compute_mean_ci <- function(d) {
  # Compute 95% CI for the mean difference in BIC for a_1 and a_2.

#  if (shapiro.test(d$bic_a1)$p.value >= 0.05 && shapiro.test(d$bic_a2)$p.value >= 0.05) {
    t_res <- t.test(d$bic_a1, d$bic_a2, paired = TRUE, alternative = "two.sided")
    mean_ci <- list(test.type = "t-test", conf.int = t_res$conf.int, p.value = t_res$p.value, statistic = t_res$statistic)
#  } else {
#    b1 <- boot(d$bic_diff, function(u, i) mean(u[i]), R = 1000)
#    b_res <- boot.ci(b1, type = c("norm"))
#    mean_ci <- list(test.type = "bootstrap", conf.int = c(b_res$normal[2], b_res$normal[3]), R.value = b_res$R)
#  }
  
  return(mean_ci)
}
```

Bar-chart with pairwise better, equal, worse BICs for a_1 and a_2 models

```{r}
library(ggplot2)
library(ggh4x)
library(scales)

plot_bic_difference_categories <- function(d, mean_ci, curve_name, m, n) {
  d$bic_diff_cats <- cut(d$bic_diff, c(-Inf, -0.5, 0.5, Inf), c("Worse", "Equally good", "Better"), right = FALSE) 
  
  
  print(paste("BIC diff cats: ",   d %>% group_by(bic_diff_cats) %>% summarise(count=n())))
  
  title <- paste("'Results Categorized by'~BIC[1]~-~BIC[2]", sep = "")

  if (mean_ci$test.type == "t-test") {
    p_str <- paste("p = ", signif(mean_ci$p.value, digits = 3), sep = "")
  } else {
    p_str <- paste("R = ", signif(mean_ci$R.value, digits = 3), sep = "")
  }
 
  ci_str <- paste(" 95% CI[", signif(mean_ci$conf.int[1], digits = 3), ", ", signif(mean_ci$conf.int[2], digits = 3), "]", sep = "")
  
  m_n_str <- ""
  #m_n_str <- paste(m, " samples of n = ", n, ", ", sep = "")
  
#  subtitle <- paste("'", m_n_str, mean_ci$test.type, "'~mu~'", ci_str, ", ", p_str, "'", sep = "")
#  subtitle <- paste("'", m_n_str, "'~mu~'", ci_str, ", ", p_str, "'", sep = "")

  
  fig_cats <- ggplot(d, aes(x = bic_diff_cats)) + 
    force_panelsizes(rows = unit(2, "in"), cols = unit(3.5, "in")) +
    theme_bw() +
    geom_bar() +
    ggtitle(parse_format()(title)) + #, parse_format()(subtitle)) +
    xlab("Differences <= |1| are equally good") + 
    ylab("Count")  
  
  return(fig_cats)
}

```

Process results grouped by generator and sample size

```{r}
library(purrr)

num_generators <- length(generators)
num_sample_sizes <- length(sample_sizes)

process_result_group <- function(generator_and_size_index) {
  generator_index <- generator_and_size_index[[1]]
  sample_size_index <- generator_and_size_index[[2]]
  
  curve_name <- generators[[generator_index]]$name
  B <- samples_per_set
  n <- sample_sizes[[sample_size_index]]
  
  d <- df_all_results[df_all_results$generator_index == generator_index & df_all_results$generator_sample_index == sample_size_index, ]

  
  print(curve_name)  
  
  # Compute confidence intervals for the mean pairwise difference in BIC scores for a_1 and a_2 models
  mean_ci <- compute_mean_ci(d)
  print("BIC")
  print(mean_ci)
  
  # Plot bar-chart with categories better, equal, worse BIC scores for a_2 compared to a_1
#  fig <- plot_bic_difference_categories(d, mean_ci, curve_name, B, n)
#  plot(fig)
  
  # Save plots
#  fig_file_name <- paste("figs_", experiment_finished_time, "/", curve_name, "_", B, "_", n, "_%s_s_", seed,".png",sep = "")
#  fig_file_name <- gsub("[ :-]", "_", fig_file_name)
#  fig_file_name <- paste("", tolower(fig_file_name), sep = "")
  
#  ggsave(gsub("[, ]", "", toString(sprintf(fig_file_name, "bic"))), plot = fig, device = "png", dpi = "print", height = 3, width = 4)
  
  t_res <- t.test(d$p_a1, d$p_a2, paired = TRUE, alternative = "two.sided")
  mean_ci <- list(test.type = "t-test", conf.int = t_res$conf.int, p.value = t_res$p.value, statistic = t_res$statistic)

  print("Performance")
  print(mean_ci)
  format(mean_ci$p.value, scientific = TRUE)

  
#  print(paste("Is p-value exactly 0? ", identical(mean_ci$p.value, integer(0))))
#  print(sprintf("The number is %.1000f", mean_ci$p.value))
  
  print(paste("mean knot diff: ", mean(d$nknots_diff)))
}

generator_and_size_indices <- expand.grid(1:num_generators, 1:num_sample_sizes, KEEP.OUT.ATTRS = TRUE) %>% purrr::transpose()

res <- lapply(generator_and_size_indices, process_result_group)

```

```{r}
generator_index <- 4
sample_size_index <- 1
func_name = "trigonometric"
  
d <- df_all_results[df_all_results$generator_index == generator_index & df_all_results$generator_sample_index == sample_size_index, ]
summary(d %>% select(p_a1, p_a2))
```

```{r}
fig <- ggplot(d) +
#  force_panelsizes(rows = unit(2, "in"), cols = unit(3.5, "in")) +
  theme_bw() +
  geom_density(aes(x = p_a2, linetype = "p_a2"), color = "black", fill = "gray50", alpha = 0.3) +
  geom_density(aes(x = p_a1, linetype = "p_a1"), color = "black", fill = "gray70", alpha = 0.3) +
  scale_linetype_manual(
    values = c("p_a1" = "dashed", "p_a2" = "solid"), 
    labels = c("p_a1" = "a1", "p_a2" = "a2")) +  
  scale_fill_grey(start = 0.3, end = 0.7, name = "Density Plot") +
  scale_color_grey(start = 0.3, end = 0.7, name = "Density Plot") +
  guides(linetype = guide_legend(title = "Approach")) +
  ggtitle("Perfomance Distributions") +
  xlab("Performance Measure") +
  ylab("Density") +
  theme(legend.position = "bottom")

ggsave(paste0("figs/peformance_density_plots_", func_name, ".png", sep = ""), plot = fig, device = "png", dpi = "print", height = 3, width = 4)

```

```{r}
library(reshape2)
library(dplyr)

d_bic_groups <- d[c("bic_a1", "bic_a2")] %>%
  rename("a1" = "bic_a1", "a2" = "bic_a2")

d_bic_groups <- melt(d_bic_groups)

fig <- ggplot(d_bic_groups, aes(x = variable, y = value, linetype = variable)) +
    theme_bw() +
    geom_violin(width = 1, fill = NA) +
    geom_boxplot(width = 0.2, color = "black", alpha = 0.2, fill = NA, show.legend = FALSE, linetype = "solid") +
    scale_linetype_manual(
        values = c("a2" = "dashed", "a1" = "dotted")
    ) +
    theme(
      legend.position = "bottom"
    ) +
    ggtitle("BIC Distributions") +
    xlab("") +
    ylab("BIC") +
    guides(linetype = guide_legend(title="Algorithm"))

print(fig)
ggsave(paste0("figs/bic_plots_", func_name, ".png", sep = ""), plot = fig, device = "png", dpi = "print", height = 3, width = 4)
```

```{r}
d_perf_groups <- d[c("p_a1", "p_a2")] %>%
  rename("a1" = "p_a1", "a2" = "p_a2")

d_perf_groups <- melt(d_perf_groups)

fig <- ggplot(d_perf_groups, aes(x = variable, y = value, linetype = variable)) +
    theme_bw() +
    geom_violin(width = 1, fill = NA) +
    geom_boxplot(width = 0.2, color = "black", alpha = 0.2, fill = NA, show.legend = FALSE, linetype = "solid") +
    scale_linetype_manual(
        values = c("a2" = "dashed", "a1" = "dotted")
    ) +
    theme(
      legend.position = "bottom"
    ) +
    ggtitle("Performance Distributions") +
    xlab("") +
    ylab("Performance") +
    guides(linetype = guide_legend(title="Algorithm"))

print(fig)
ggsave(paste0("figs/performance_plots_", func_name, ".png", sep = ""), plot = fig, device = "png", dpi = "print", height = 3, width = 4)
```
